// Generated from docs/api/core-api.openapi.json. Keep operation IDs in sync with pnpm openapi:check.

export const CORE_API_OPERATIONS = [
  {
    method: 'POST',
    operationId: 'advanceWorkerOnboardingCase',
    path: '/v1/operator/worker-onboarding-cases/{caseId}/advance',
    pathParameters: ['caseId'],
    tags: ['operator'],
  },
  {
    method: 'POST',
    operationId: 'assignSubscriptionWorker',
    path: '/v1/subscriptions/{subscriptionId}/assignment',
    pathParameters: ['subscriptionId'],
    tags: ['subscriptions'],
  },
  {
    method: 'POST',
    operationId: 'cancelSubscription',
    path: '/v1/subscriptions/{subscriptionId}/cancel',
    pathParameters: ['subscriptionId'],
    tags: ['subscriptions'],
  },
  {
    method: 'POST',
    operationId: 'changeSubscriptionTier',
    path: '/v1/subscriptions/{subscriptionId}/tier',
    pathParameters: ['subscriptionId'],
    tags: ['subscriptions'],
  },
  {
    method: 'POST',
    operationId: 'chargeSubscriptionMock',
    path: '/v1/subscriptions/{subscriptionId}/mock-charge',
    pathParameters: ['subscriptionId'],
    tags: ['subscriptions'],
  },
  {
    method: 'POST',
    operationId: 'checkInVisit',
    path: '/v1/visits/{visitId}/check-in',
    pathParameters: ['visitId'],
    tags: ['visits'],
  },
  {
    method: 'POST',
    operationId: 'checkOutVisit',
    path: '/v1/visits/{visitId}/check-out',
    pathParameters: ['visitId'],
    tags: ['visits'],
  },
  {
    method: 'POST',
    operationId: 'createOperatorSubscriberPrivacyRequest',
    path: '/v1/operator/subscriptions/{subscriptionId}/privacy-requests',
    pathParameters: ['subscriptionId'],
    tags: ['operator'],
  },
  {
    method: 'POST',
    operationId: 'createOperatorWorkerMonthlyPayout',
    path: '/v1/operator/workers/{workerId}/monthly-payouts',
    pathParameters: ['workerId'],
    tags: ['operator'],
  },
  {
    method: 'POST',
    operationId: 'createSubscription',
    path: '/v1/subscriptions',
    pathParameters: [],
    tags: ['subscriptions'],
  },
  {
    method: 'POST',
    operationId: 'createVisitDispute',
    path: '/v1/subscriptions/{subscriptionId}/visits/{visitId}/disputes',
    pathParameters: ['subscriptionId', 'visitId'],
    tags: ['subscriptions'],
  },
  {
    method: 'POST',
    operationId: 'createVisitPhotoUpload',
    path: '/v1/visits/{visitId}/photo-uploads',
    pathParameters: ['visitId'],
    tags: ['visits'],
  },
  {
    method: 'POST',
    operationId: 'createWorkerAdvanceRequest',
    path: '/v1/workers/{workerId}/advance-requests',
    pathParameters: ['workerId'],
    tags: ['workers'],
  },
  {
    method: 'POST',
    operationId: 'createWorkerOnboardingCase',
    path: '/v1/operator/worker-onboarding-cases',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'POST',
    operationId: 'createWorkerSwapRequest',
    path: '/v1/subscriptions/{subscriptionId}/worker-swap-requests',
    pathParameters: ['subscriptionId'],
    tags: ['subscriptions'],
  },
  {
    method: 'POST',
    operationId: 'createWorkerUnavailability',
    path: '/v1/workers/{workerId}/unavailability',
    pathParameters: ['workerId'],
    tags: ['workers'],
  },
  {
    method: 'POST',
    operationId: 'declineAssignmentCandidate',
    path: '/v1/operator/subscriptions/{subscriptionId}/assignment-decisions',
    pathParameters: ['subscriptionId'],
    tags: ['operator'],
  },
  {
    method: 'POST',
    operationId: 'deliverDueOperatorNotifications',
    path: '/v1/operator/notifications/deliver-due',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'getHealth',
    path: '/health',
    pathParameters: [],
    tags: ['system'],
  },
  {
    method: 'GET',
    operationId: 'getOperatorBetaMetrics',
    path: '/v1/operator/beta-metrics',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'getOperatorSubscriptionSupportContext',
    path: '/v1/operator/subscriptions/{subscriptionId}/support-context',
    pathParameters: ['subscriptionId'],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'getPaymentProviderReadiness',
    path: '/v1/operator/payment-provider-readiness',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'getPushProviderReadiness',
    path: '/v1/operator/push-provider-readiness',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'getReadiness',
    path: '/ready',
    pathParameters: [],
    tags: ['system'],
  },
  {
    method: 'GET',
    operationId: 'getSubscriptionDetail',
    path: '/v1/subscriptions/{subscriptionId}',
    pathParameters: ['subscriptionId'],
    tags: ['subscriptions'],
  },
  {
    method: 'GET',
    operationId: 'getWorkerEarnings',
    path: '/v1/workers/{workerId}/earnings',
    pathParameters: ['workerId'],
    tags: ['workers'],
  },
  {
    method: 'GET',
    operationId: 'getWorkerProfile',
    path: '/v1/workers/{workerId}/profile',
    pathParameters: ['workerId'],
    tags: ['workers'],
  },
  {
    method: 'GET',
    operationId: 'getWorkerRoute',
    path: '/v1/workers/{workerId}/route',
    pathParameters: ['workerId'],
    tags: ['workers'],
  },
  {
    method: 'POST',
    operationId: 'ingestPaymentWebhook',
    path: '/v1/payments/webhooks',
    pathParameters: [],
    tags: ['payments'],
  },
  {
    method: 'POST',
    operationId: 'issueOperatorPaymentRefund',
    path: '/v1/operator/payment-attempts/{paymentAttemptId}/refunds',
    pathParameters: ['paymentAttemptId'],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listLomePricing',
    path: '/v1/pricing/lome',
    pathParameters: [],
    tags: ['pricing'],
  },
  {
    method: 'GET',
    operationId: 'listOperatorAuditEvents',
    path: '/v1/operator/audit-events',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listOperatorDisputes',
    path: '/v1/operator/disputes',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listOperatorMatchingQueue',
    path: '/v1/operator/matching-queue',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listOperatorNotifications',
    path: '/v1/operator/notifications',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listOperatorPaymentAttempts',
    path: '/v1/operator/payment-attempts',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listOperatorPushDevices',
    path: '/v1/operator/push-devices',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listOperatorServiceCells',
    path: '/v1/operator/service-cells',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listOperatorSubscriberSupportMatches',
    path: '/v1/operator/subscriber-support-matches',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listOperatorWorkerAdvanceRequests',
    path: '/v1/operator/worker-advance-requests',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listOperatorWorkerIssues',
    path: '/v1/operator/worker-issues',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listOperatorWorkerSwapRequests',
    path: '/v1/operator/worker-swap-requests',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listSubscriptionBillingHistory',
    path: '/v1/subscriptions/{subscriptionId}/billing-history',
    pathParameters: ['subscriptionId'],
    tags: ['subscriptions'],
  },
  {
    method: 'GET',
    operationId: 'listSubscriptionMatchingCandidates',
    path: '/v1/operator/subscriptions/{subscriptionId}/matching-candidates',
    pathParameters: ['subscriptionId'],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listWorkerAdvanceRequests',
    path: '/v1/workers/{workerId}/advance-requests',
    pathParameters: ['workerId'],
    tags: ['workers'],
  },
  {
    method: 'GET',
    operationId: 'listWorkerOnboardingCases',
    path: '/v1/operator/worker-onboarding-cases',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'GET',
    operationId: 'listWorkerPayouts',
    path: '/v1/workers/{workerId}/payouts',
    pathParameters: ['workerId'],
    tags: ['workers'],
  },
  {
    method: 'GET',
    operationId: 'listWorkerUnavailability',
    path: '/v1/workers/{workerId}/unavailability',
    pathParameters: ['workerId'],
    tags: ['workers'],
  },
  {
    method: 'PUT',
    operationId: 'putLocalObjectStorageObject',
    path: '/local-object-storage/{objectKey}',
    pathParameters: ['objectKey'],
    tags: ['local-object-storage'],
  },
  {
    method: 'POST',
    operationId: 'rateVisit',
    path: '/v1/subscriptions/{subscriptionId}/visits/{visitId}/rating',
    pathParameters: ['subscriptionId', 'visitId'],
    tags: ['subscriptions'],
  },
  {
    method: 'POST',
    operationId: 'recordVisitPhoto',
    path: '/v1/visits/{visitId}/photos',
    pathParameters: ['visitId'],
    tags: ['visits'],
  },
  {
    method: 'POST',
    operationId: 'refreshAuthSession',
    path: '/v1/auth/refresh',
    pathParameters: [],
    tags: ['auth'],
  },
  {
    method: 'POST',
    operationId: 'registerPushDevice',
    path: '/v1/devices/push-token',
    pathParameters: [],
    tags: ['devices'],
  },
  {
    method: 'POST',
    operationId: 'reportWorkerIssue',
    path: '/v1/visits/{visitId}/worker-issues',
    pathParameters: ['visitId'],
    tags: ['visits'],
  },
  {
    method: 'POST',
    operationId: 'rescheduleVisit',
    path: '/v1/subscriptions/{subscriptionId}/visits/{visitId}/reschedule',
    pathParameters: ['subscriptionId', 'visitId'],
    tags: ['subscriptions'],
  },
  {
    method: 'POST',
    operationId: 'resolveOperatorDispute',
    path: '/v1/operator/disputes/{disputeId}/resolve',
    pathParameters: ['disputeId'],
    tags: ['operator'],
  },
  {
    method: 'POST',
    operationId: 'resolveOperatorWorkerAdvanceRequest',
    path: '/v1/operator/worker-advance-requests/{requestId}/resolve',
    pathParameters: ['requestId'],
    tags: ['operator'],
  },
  {
    method: 'POST',
    operationId: 'resolveOperatorWorkerIssue',
    path: '/v1/operator/worker-issues/{issueId}/resolve',
    pathParameters: ['issueId'],
    tags: ['operator'],
  },
  {
    method: 'POST',
    operationId: 'resolveOperatorWorkerSwapRequest',
    path: '/v1/operator/worker-swap-requests/{requestId}/resolve',
    pathParameters: ['requestId'],
    tags: ['operator'],
  },
  {
    method: 'POST',
    operationId: 'runOperatorPaymentReconciliation',
    path: '/v1/operator/payment-reconciliation-runs',
    pathParameters: [],
    tags: ['operator'],
  },
  {
    method: 'POST',
    operationId: 'skipVisit',
    path: '/v1/subscriptions/{subscriptionId}/visits/{visitId}/skip',
    pathParameters: ['subscriptionId', 'visitId'],
    tags: ['subscriptions'],
  },
  {
    method: 'POST',
    operationId: 'startOtpChallenge',
    path: '/v1/auth/otp/start',
    pathParameters: [],
    tags: ['auth'],
  },
  {
    method: 'POST',
    operationId: 'updateOperatorVisitStatus',
    path: '/v1/operator/visits/{visitId}/status',
    pathParameters: ['visitId'],
    tags: ['operator'],
  },
  {
    method: 'PUT',
    operationId: 'upsertOperatorWorkerProfile',
    path: '/v1/operator/workers/{workerId}/profile',
    pathParameters: ['workerId'],
    tags: ['operator'],
  },
  {
    method: 'POST',
    operationId: 'verifyOtpChallenge',
    path: '/v1/auth/otp/verify',
    pathParameters: [],
    tags: ['auth'],
  },
] as const;

export type CoreApiOperation = (typeof CORE_API_OPERATIONS)[number];
export type CoreApiOperationId = CoreApiOperation['operationId'];
export type CoreApiMethod = CoreApiOperation['method'];
